language: objective-c
osx_image: xcode7.3
before_install:
  - gem install slather
  - xcrun simctl list
install: 
  - echo "<3"
  - git clone https://github.com/facebook/xctool.git
env:
  - MODE=tests
  - MODE=build
before_script:
 - chmod +x build.sh
script: 
 - ./build.sh $MODE
after_success:
  - slather

# whitelist
branches:
  only:
    - master
