language: objective-c
osx_image: xcode7.3
before_install:
  - brew update
  - brew reinstall xctool
  - brew reinstall carthage
  - gem install cocoapods -v 0.39.0
  - gem install xcodeproj -v 0.28.2
  - gem install slather
  - xcrun simctl list
install: echo "<3"
env:
  - MODE=tests
  - MODE=build
before_script:
 - chmod +x build.sh
script: ./build.sh $MODE
after_success:
  - slather

# whitelist
branches:
  only:
    - master
